### ISSUE TITLE
Delete old archived repos

### ISSUE THREAD

**Issue by bryevdv** [bokeh/pm#10]
We currently have a half-dozen archived repos:

<img width="1177" alt="Screenshot 2023-10-11 at 13 50 27" src="https://github.com/bokeh/pm/assets/1078448/ffd5fe6c-4321-4708-8118-e454dcb1942f">

Can some of these be deleted? I'd like newcomers to the Bokeh org to be confronted with as little irrelevant and useless informatio as possible. Offhand I personally think these could *definitely* de deleted:

* `blog.bokeh.org` (useless, all material copied over to medium at this point)
* `bokehplots.com` (useless, nothing relevant or useful for most of a decade here)
* `bkcharts` (completely irrelevant today)

It seems like there may be others archived soon (e.g. RBokeh and possibly some vendored dependencies). Would it be reasonable to make a `bokeh-attic` GH Org to move old archived repositories to? That would include vendored dependencies archived more than two minor releases ago. since we would never expect to make any more point releases on those branches ever. In the highly, extremely unlikely event that we did need them, the repos would technically still be accessible with some effort. 

cc @bokeh/core

**Comment by bryevdv** [comment]
noting I plan to delete `bokeh/badges` in the very near future as well -- the conda download badge generation does not work anymore and SO badge generation is no longer needed (shields.io picked it up)

**Comment by bryevdv** [comment]
Also asked in Slack but maybe here is better:

> Does anyone know why we have a fork of distributed in the Bokeh org? https://github.com/bokeh/distributed It does not seem to be different from the main distributed repo in any way or therefor serve any purpose. I would like to propose deleting it

**Comment by bryevdv** [comment]
It also only just occurs to me that `bokeh/bokeh-notebooks` has been superseded by `bokeh/tutorial` and could at least be archived with a pointer to the new repo?

**Comment by ianthomas23** [comment]
> noting I plan to delete `bokeh/badges` in the very near future as well -- the conda download badge generation does not work anymore and SO badge generation is no longer needed (shields.io picked it up)

I know how to fix the error generating the conda badge if you would like to keep that part of the process?

**Comment by bryevdv** [comment]
> if you would like to keep that part of the process?

To be honest, not really. It was unreliable even when it did "work" owing to uncertainty when the data was published. But more importantly, GH has taken a stance against being everyone's cron job. GH actions are disabled in any repo that does not see activity for two months (I had to re-enable manually in settings yesterday). It's just a badge, not that important. If we need numbers for grant applications, etc. we can derive them at the time.

**Comment by pavithraes** [comment]
I'm +1 to archiving `bokeh/bokeh-notebooks` and deleting `bokeh/distributed` (also don't know why this is here, and I couldn't also added it accidentally)

**Comment by bryevdv** [comment]
@bokeh/core I'll plan on taking these actions by the end of the week unless there's a discussion opened:

* archive `bokeh/notebooks`
* delete `bokeh/distributed`
* delete `bokeh/blog.bokeh.org`
* delete `bokeh/bokehplots.com`

**Comment by bryevdv** [comment]
I'll make a new issues about moving archived repos to a new `bokeh-attic` org or similar at some other time in the future, no real hurry.
