### ISSUE TITLE
intern project ideas

### ISSUE THREAD

**Issue by brainwane** [bokeh/pm#2]
@bryevdv Somewhere within Bokeh's documentation, wiki, repositories, or elsewhere, please start a listing of little project ideas for Google Summer of Code/[Outreachy](https://outreachy.org/)/[LFX](https://docs.linuxfoundation.org/lfx/mentorship/) interns.

The first one on the list: creating [a JOSS item for Bokeh](https://joss.theoj.org/), to get a DOI for researchers to cite.

**Comment by bryevdv** [comment]
https://github.com/bokeh/bokeh/wiki/Outreachy-Project-Ideas
